# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='empid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='teamlead',
            field=models.BooleanField(default=False, verbose_name='Team Lead'),
        ),
        migrations.AddField(
            model_name='user',
            name='skillset',
            field=models.ManyToManyField(to='account.Skill'),
        ),
    ]
