# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170915_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skillset',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
